"""Add Vertexai setting columns

Revision ID: 0daad103feb5
Revises: 5ebb82b7befa
Create Date: 2026-02-14 09:43:05.377647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daad103feb5'
down_revision: Union[str, Sequence[str], None] = '5ebb82b7befa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_project_id_vertexai', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gemini_location_vertexai', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_location_vertexai')
    op.drop_column('users', 'gemini_project_id_vertexai')
    # ### end Alembic commands ###
