"""rename api_key_encypted to gemini_api_key_encrypted

Revision ID: 1209a9f87899
Revises: 66413c766e65
Create Date: 2025-12-28 23:17:00.813605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1209a9f87899'
down_revision: Union[str, Sequence[str], None] = '66413c766e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gemini_api_key_updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'api_key_updated_at')
    op.drop_column('users', 'api_key_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('api_key_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'gemini_api_key_updated_at')
    op.drop_column('users', 'gemini_api_key_encrypted')
    # ### end Alembic commands ###
