"""add gemini_api_key_vertexai columns

Revision ID: 5ebb82b7befa
Revises: 1209a9f87899
Create Date: 2025-12-29 11:37:50.584881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebb82b7befa'
down_revision: Union[str, Sequence[str], None] = '1209a9f87899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_api_key_vertexai_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gemini_api_key_vertexai_updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_api_key_vertexai_updated_at')
    op.drop_column('users', 'gemini_api_key_vertexai_encrypted')
    # ### end Alembic commands ###
