"""add uwgen_api_key columns

Revision ID: 66413c766e65
Revises: 3d4c8eb31a49
Create Date: 2025-12-27 08:29:40.966160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66413c766e65'
down_revision: Union[str, Sequence[str], None] = '3d4c8eb31a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uwgen_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('uwgen_api_key_updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['uwgen_api_key'], schema='uwgen')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='uwgen', type_='unique')
    op.drop_column('users', 'uwgen_api_key_updated_at')
    op.drop_column('users', 'uwgen_api_key')
    # ### end Alembic commands ###
